name: Debug Affirmation Bot
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- show first lines of affirmations.txt (if exists) ----"
          [ -f affirmations.txt ] && head -n 5 affirmations.txt || echo "No affirmations.txt"

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run bot once (no commit)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python send_affirmation.py
